Исправила баг обработки сообщения веб-сокета.
VikSing88/MattermostBot pull request #4
Opened 2022-03-15 10:36 UTC by VikSing88

* Исправила баг обработки сообщения веб-сокета. Теперь если сообщение больше выделенного буфера, то оно будет считываться частями, пока не наступит конец сообщения. И только после этого будет парситься.
+ Добавила обработчик ошибок. Сейчас ошибка просто выводится на консоль. При запуске бота из планировщика в этом смысла особого нет, но потом можно будет выводить ошибки в лог.

2022-03-17 10:15 UTC, aledyad requested changes

2022-03-17 10:15 UTC, aledyad commented on MattermostBot/MattermostApiAdapter.cs
> +            if (responce.EndOfMessage)
Получение полного сообщения реализуется за счет цикла while(!cancellationToken), что некрасиво, т.к. цикл while отвечает за более глобальную задачу - обрабатывать сообщения, пока не стопнули.

Получение полного тела сообщения лучше сделать отдельным циклом do ... while (см. пример https://stackoverflow.com/questions/23773407/a-websockets-receiveasync-method-does-not-await-the-entire-message).

2022-03-17 10:15 UTC, aledyad commented on MattermostBot/MattermostApiAdapter.cs
> +          const int maxBufferSize = 1000;
Такой маленький буфер это несерьезно.
64К было бы в самый раз.

2022-03-22 07:21 UTC, VikSing88 commented on MattermostBot/MattermostApiAdapter.cs
> +            if (responce.EndOfMessage)
Переделала.

2022-03-22 07:21 UTC, VikSing88 commented on MattermostBot/MattermostApiAdapter.cs
> +          const int maxBufferSize = 1000;
Поправила.

2022-03-23 10:35 UTC, aledyad approved these changes

2022-03-23 10:35 UTC, aledyad commented on MattermostBot/MattermostApiAdapter.cs
> +          const int maxBufferSize = 1000;
Вообще 64к это 64*1024. Не критично)

2022-03-23 10:36 UTC, merged